---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key
  data:
  - secretKey: secret_key
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: authentik_secret_key
      property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-mail
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-mail
  data:
  - secretKey: from
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: authentik_mail
      property: from
  - secretKey: host
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: authentik_mail
      property: host
  - secretKey: username
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: authentik_mail
      property: username
  - secretKey: password
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: authentik_mail
      property: password
