apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.engiqueer.net:8200"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVRUZvU1Y3WDJHRTVLUGsxeFFSdUhnYWtCNGljd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF4TVZaVzVuYVhGMVpXVnlMbTVsZENCU2IyOTBJRU5CTUI0WERUSTFNRFl5T0RFMQpNemt3TjFvWERUTTFNRFl5TmpFMU16a3pObG93SURFZU1Cd0dBMVVFQXhNVlpXNW5hWEYxWldWeUxtNWxkQ0JTCmIyOTBJRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxOVdhVVhHNEsvYmMKTkxFdDhLTkpPallaNHljMWQyYllJT2JRY1h0NkpLQ0EzVEZsUlBvYVp0MXg5cVg2MUszU0pZRDB5aVpaKzl6cQoxbEJUbWhaYVd2M2p4TytmbFg4ZzVyUWxTVnJIc0s2b0lxSHFKZm5OQndGbjNaZGxwMkxDanNXTHhOeXg2OFFvCmxnNE5SeUFBV0VRTTN6cXNtczVDa0NMKytYZ1FzTHZ5dnZaUmdGV2xyQVJ0bHZuZXVMTXdYUEl0dzI5WUxPQlMKWWpqU29BUEVSSk5CTHR6cUNvU0xFYitPbS94MWczVjMwZWEvTlB1OWwzb3dqdVBvaUpobTRBRThnU1ZOaGpPdwp5TVBhV0NNc1VyWjVsWUlWc1hGc2Mxc0M2WDRrRG9iUTEyUWhEbFdtbmZybzNRbGg0d1hTL09qTDVOTEhMQkRTCk9CajNNbVRabndJREFRQUJvMk13WVRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVorb2hlemhMY0NLNWVzaDlvSXBmZDNja1h4SXdId1lEVlIwakJCZ3dGb0FVWitvaAplemhMY0NLNWVzaDlvSXBmZDNja1h4SXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSWhkUHZzMVlCWU9oSzBkCmRoUGx3eDByWlNwbW00SU90b1hLeFFlOVJNamxuYlZNU1dobWV0MWsvVXpGa09WMjVQSVNmbFQ4djczMUJaTGUKMTJDMmd3QWpCSFZVeEdiVnhRMG9qbS85RlNhN0tBbXpUOGFUYlQwc2FwUkZwdVdUY2U3SEd3NFd6Ukxqd2hkRApLRWNhWCtuTk5OMy81a2taN29iTnVpS2k0MVhFeFN2bDVkd2RvelZUY0pqaUxwdlppYTlrNEtkODk5TkNGVzN5CldUT0ppWVd1ZnU1WDZCMkQ4TFA4U2VQMDIzV3FEay9ISTQ4Tlc5TFFYVmo0VFhhREJVaUlTYTRRQkFpZjJFN1QKNnRzSHRYSjB0eTlIUGVZWTJBRWYwWWJGMUp5WEhxZUlJQWxnRWMrRXNnbCtDZWkwVDhRTXhDQTE0K1FqZWU4QwpMRGhKQmlJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
      path: "ukgovcamp"
      version: "v2"
      auth:
        appRole:
          roleId: 6ff156a2-7f5a-1046-c776-3be8c66b9c5f
          secretRef:
            name: vault-config
            namespace: external-secrets
            key: secret-id
